# Generated by Django 3.2.10 on 2022-01-07 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seater', models.CharField(max_length=100, null=True)),
                ('room_no', models.CharField(max_length=100, null=True)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=50, null=True)),
                ('contactNo', models.CharField(max_length=15, null=True)),
                ('regDate', models.DateField(null=True)),
                ('updationDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayfrom', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('egycontactno', models.CharField(max_length=15, null=True)),
                ('corresAddress', models.CharField(max_length=350, null=True)),
                ('corresCIty', models.CharField(max_length=100, null=True)),
                ('pmntAddress', models.CharField(max_length=350, null=True)),
                ('pmntCity', models.CharField(max_length=100, null=True)),
                ('postingDate', models.DateField(null=True)),
                ('updationDate', models.DateField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.courses')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.rooms')),
                ('userreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.userregistration')),
            ],
        ),
    ]
