# Generated by Django 3.2.10 on 2022-01-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='room',
            new_name='rooms',
        ),
        migrations.RenameField(
            model_name='userregistration',
            old_name='user',
            new_name='users',
        ),
    ]
