# Generated by Django 3.2.10 on 2022-01-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_auto_20220108_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='regNo',
            field=models.IntegerField(null=True),
        ),
    ]
