# Generated by Django 4.0.1 on 2022-01-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_userregistration_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='type',
            field=models.CharField(choices=[('s', 'Sports Room'), ('l', 'Laundry Room')], max_length=10, null=True),
        ),
    ]
