# Generated by Django 4.0.1 on 2022-01-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_rooms_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='corresAddress',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='corresCIty',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='corresPincode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='corresState',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='foodstatus',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pmnatetState',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pmntAddress',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pmntCity',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pmntPincode',
        ),
        migrations.AlterField(
            model_name='registration',
            name='postingDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updationDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
