# Generated by Django 4.0.1 on 2022-01-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_remove_registration_corresaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='regNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
